name: .NET Core Code Coverage
 
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
      - '**/common.props'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'
      - '**/stylecop.props'
      - '**/stylecop.ruleset'
      - '**/stylecop.json'
      - '**/common.props'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Mon-Ami.Server
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Create Code Coverage Report
      run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish Code Coverage Report
      uses: coverallsapp/github-action@v1.0.1
      with:
       github-token: ${{ secrets.github_token }}
       file: ./coverage.xml
       directory: ./coverage/reports/
       flags: unittests
       env_vars: OS,C#
       fail_ci_if_error: true
       path_to_write_report: ./coverage/codecov_report.txt
       verbose: true
